version: "3.9"

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: Deneme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: me@de.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"

volumes:
  pgdata: